### ISSUE TITLE
What is the Inference time in GPU?

### ISSUE THREAD

**Issue by ajaysg-zz** [geneing/WaveRNN-Pytorch#13]
if the model is able to produce 7 seconds of audio in 5 seconds in CPU. How long will it be in GPU. Please throw some light on this.

**Comment by geneing** [comment]
GPU doesn't help much with inference, unless you use the batching trick https://github.com/fatchord/WaveRNN. If latency is not an issue (i.e. you are synthesizing a very long mel-spectrogram), then speedup with batching trick depends only on the memory/sm count of your GPU. If you need low latency, then pruning and quantization and CPU code vectorization will give you faster than real time inference.
