### ISSUE TITLE
eigen3 error

### ISSUE THREAD

**Issue by maozhiqiang** [geneing/WaveRNN-Pytorch#3]
hi @geneing Thank you for your contribution,I used cmake to build , But the following error occurred 
 Target "vocoder" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
how to fixed this ! thanks

**Comment by geneing** [comment]
You need to install eigen3 library. If you are using Ubuntu 18.04, the command is
sudo apt-get install libeigen3-dev

**Comment by maozhiqiang** [comment]
I recompiled it, and now it's settled. Thank you.
